satDataFolder="/sat/"
trainingDataFolder="/train/"
checkDataFolder="/check/"
testDataFolder="/test/"
featureDataFolder="/feature/"
modelDataFolder="/models/"
weightDataFolder="/weights/"
indexDataFolder="/imgindex/"
